package symbols

const (
	// fiat
	Aud = "AUD"
	Cad = "CAD"
	Clp = "CLP"
	Cny = "CNY"
	Cop = "COP"
	Eur = "EUR"
	Gbp = "GBP"
	Hkd = "HKD"
	Idr = "IDR"
	Jpy = "JPY"
	Krw = "KRW"
	Myr = "MYR"
	Ngn = "NGN"
	Nzd = "NZD"
	Pen = "PEN"
	Php = "PHP"
	Pln = "PLN"
	Sgd = "SGD"
	Thb = "THB"
	Usd = "USD"
	Zar = "ZAR"

	// crypto
	Ada   = "ADA"   // Cardano              https://coinmarketcap.com/currencies/cardano/
	Adt   = "ADT"   // adToken              https://coinmarketcap.com/currencies/adtoken/
	Adx   = "ADX"   // AdEx                 https://coinmarketcap.com/currencies/adx-net/
	Aur   = "AUR"   // Auroracoin
	Bch   = "BCH"   // Bcash
	Blk   = "BLK"   // BlackCoin
	Btc   = "BTC"   // Bitcoin
	Btg   = "BTG"   // Bgold
	Bts   = "BTS"   // BitShares
	Cloak = "CLOAK" // CloakCoin
	Cure  = "CURE"  // Curecoin
	Cvc   = "CVC"   // Civic                https://coinmarketcap.com/currencies/civic/
	Dash  = "DASH"  // Dash
	Dgb   = "DGB"   // DigiByte             https://coinmarketcap.com/currencies/digibyte/
	Dnt   = "DNT"   // district0x           https://coinmarketcap.com/currencies/district0x/
	Doge  = "DOGE"  // Dogecoin
	Efl   = "EFL"   // e-Gulden
	Emc2  = "EMC2"  // Einsteinium
	Eng   = "ENG"   // Enigma               https://coinmarketcap.com/currencies/enigma-project/
	Enrg  = "ENRG"  // Energycoin
	Eos   = "EOS"   // EOS
	Erc   = "ERC"   // EuropeCoin
	Etc   = "ETC"   // Ethereum Classic
	Eth   = "ETH"   // Ethereum
	Evx   = "EVX"   // Everex
	Fct   = "FCT"   // Factom               https://coinmarketcap.com/currencies/factom/
	Ftc   = "FTC"   // Feathercoin
	Fuel  = "FUEL"  // Etherparty
	Fun   = "FUN"   // FunFair              https://coinmarketcap.com/currencies/funfair/
	Game  = "GAME"  // GameCredits
	Gld   = "GLD"   // GoldCoin
	Gno   = "GNO"   // Gnosis
	Grs   = "GRS"   // Groestlcoin
	Hsr   = "HSR"   // Hshare
	Hyp   = "HYP"   // HyperStake
	Icn   = "ICN"   // Iconomi
	Iota  = "IOTA"  // Iota
	Knc   = "KNC"   // Kyber Network
	Kore  = "KORE"  // Kore
	Lsk   = "LSK"   // Lisk
	Ltc   = "LTC"   // Litecoin
	Mana  = "MANA"  // Decentraland         https://coinmarketcap.com/currencies/decentraland/
	Mco   = "MCO"   // Monaco               https://coinmarketcap.com/currencies/monaco/
	Mer   = "MER"   // Mercury              https://coinmarketcap.com/currencies/mercury/
	Mln   = "MLN"   // Melon
	Mona  = "MONA"  // MonaCoin
	Mtl   = "MTL"   // Metal                https://coinmarketcap.com/currencies/metal/
	Nav   = "NAV"   // NAV Coin             https://coinmarketcap.com/currencies/nav-coin/
	Neo   = "NEO"   // Neo
	Nlg   = "NLG"   // Gulden
	Nmc   = "NMC"   // Namecoin
	Nxt   = "NXT"   // Nxt
	Omg   = "OMG"   // OmiseGO
	Part  = "PART"  // Particl              https://coinmarketcap.com/currencies/particl/
	Pay   = "PAY"   // TenX                 https://coinmarketcap.com/currencies/tenx/
	Pnd   = "PND"   // Pandacoin
	Pot   = "POT"   // PotCoin
	Powr  = "POWR"  // Power Ledger         https://coinmarketcap.com/currencies/power-ledger/
	Ppc   = "PPC"   // Peercoin
	Ptc   = "PTC"   // Pesetacoin
	Qash  = "QASH"  // Qash                 https://coinmarketcap.com/currencies/qash/
	Qrk   = "QRK"   // Quark
	Qtum  = "QTUM"  // Qtum                 https://coinmarketcap.com/currencies/qtum/
	Rby   = "RBY"   // Rubycoin
	Rcn   = "RCN"   // Ripio Credit Network https://coinmarketcap.com/currencies/ripio-credit-network/
	Rdd   = "RDD"   // ReddCoin
	Rep   = "REP"   // Augur
	Salt  = "SALT"  // SALT                 https://coinmarketcap.com/currencies/salt/
	Sc    = "SC"    // Siacoin              https://coinmarketcap.com/currencies/siacoin/
	Slr   = "SLR"   // SolarCoin
	Start = "START" // Startcoin
	Storj = "STORJ" // Storj                https://coinmarketcap.com/currencies/storj/
	Strat = "STRAT" // Stratis              https://coinmarketcap.com/currencies/stratis/
	Thc   = "THC"   // HempCoin
	Tix   = "TIX"   // Blocktix             https://coinmarketcap.com/currencies/blocktix/
	Trust = "TRUST" // TrustPlus
	Ubtc  = "UBTC"  // United Bitcoin
	Ukg   = "UKG"   // Unikoin Gold         https://coinmarketcap.com/currencies/unikoin-gold/
	Vib   = "VIB"   // Viberate             https://coinmarketcap.com/currencies/viberate/
	Vrc   = "VRC"   // VeriCoin
	Vtc   = "VTC"   // Vertcoin
	Waves = "WAVES" // Waves
	Xcn   = "XCN"   // Cryptonite
	Xdn   = "XDN"   // DigitalNote
	Xel   = "XEL"   // Elastic              https://coinmarketcap.com/currencies/elastic/
	Xem   = "XEM"   // NEM
	Xlm   = "XLM"   // stellar, lumens
	Xmr   = "XMR"   // Monero
	Xmy   = "XMY"   // Myriad
	Xpm   = "XPM"   // Primecoin
	Xpy   = "XPY"   // PayCoin
	Xvg   = "XVG"   // Verge                https://coinmarketcap.com/currencies/verge/
	Xwc   = "XWC"   // WhiteCoin
	Xzc   = "XZC"   // ZCoin
	Zec   = "ZEC"   // Zcash

	// shit
	Usdt = "USDT" // Tether
	Xrp  = "XRP"  // Ripple
	Kfee = "KFEE" // Kraken fee
)
