package symbols

const (
	// fiat
	Aud = "AUD"
	Cad = "CAD"
	Clp = "CLP"
	Cny = "CNY"
	Cop = "COP"
	Eur = "EUR"
	Gbp = "GBP"
	Hkd = "HKD"
	Idr = "IDR"
	Inr = "INR"
	Jpy = "JPY"
	Krw = "KRW"
	Myr = "MYR"
	Ngn = "NGN"
	Nzd = "NZD"
	Pen = "PEN"
	Php = "PHP"
	Pln = "PLN"
	Sgd = "SGD"
	Thb = "THB"
	Usd = "USD"
	Zar = "ZAR"

	// crypto
	Ada   = "ADA"   // Cardano                  https://coinmarketcap.com/currencies/cardano/
	Adt   = "ADT"   // adToken                  https://coinmarketcap.com/currencies/adtoken/
	Adx   = "ADX"   // AdEx                     https://coinmarketcap.com/currencies/adx-net/
	Agrs  = "AGRS"  // Agoras Tokens            https://coinmarketcap.com/currencies/agoras-tokens/
	Ant   = "ANT"   // Aragon                   https://coinmarketcap.com/currencies/aragon/
	Aur   = "AUR"   // Auroracoin
	Bat   = "BAT"   // Basic Attention Token    https://coinmarketcap.com/currencies/basic-attention-token/
	Bch   = "BCH"   // Bcash
	Bcy   = "BCY"   // Bitcrystals              https://coinmarketcap.com/currencies/bitcrystals/
	Blk   = "BLK"   // BlackCoin
	Block = "BLOCK" // Blocknet                 https://coinmarketcap.com/currencies/blocknet/#markets
	Bnt   = "BNT"   // Bancor                   https://coinmarketcap.com/currencies/bancor/
	Bsd   = "BSD"   // BitSend                  https://coinmarketcap.com/currencies/bitsend/
	Btc   = "BTC"   // Bitcoin
	Btg   = "BTG"   // Bgold
	Bts   = "BTS"   // BitShares
	Byc   = "BYC"   // Bytecent                 https://coinmarketcap.com/currencies/bytecent/
	Cfi   = "CFI"   // Cofound.it               https://coinmarketcap.com/currencies/cofound-it/
	Cloak = "CLOAK" // CloakCoin
	Crb   = "CRB"   // Creditbit                https://coinmarketcap.com/currencies/creditbit/
	Cure  = "CURE"  // Curecoin
	Cvc   = "CVC"   // Civic                    https://coinmarketcap.com/currencies/civic/
	Dash  = "DASH"  // Dash
	Dgb   = "DGB"   // DigiByte                 https://coinmarketcap.com/currencies/digibyte/
	Dgd   = "DGD"   // DigixDAO                 https://coinmarketcap.com/currencies/digixdao/
	Dnt   = "DNT"   // district0x               https://coinmarketcap.com/currencies/district0x/
	Doge  = "DOGE"  // Dogecoin
	Dope  = "DOPE"  // DopeCoin                 https://coinmarketcap.com/currencies/dopecoin/
	Dtb   = "DTB"   // Databits                 https://coinmarketcap.com/currencies/databits/
	Efl   = "EFL"   // e-Gulden
	Emc   = "EMC"   // Emercoin                 https://coinmarketcap.com/currencies/emercoin/
	Emc2  = "EMC2"  // Einsteinium
	Eng   = "ENG"   // Enigma                   https://coinmarketcap.com/currencies/enigma-project/
	Enrg  = "ENRG"  // Energycoin
	Eos   = "EOS"   // EOS
	Erc   = "ERC"   // EuropeCoin
	Etc   = "ETC"   // Ethereum Classic
	Eth   = "ETH"   // Ethereum
	Evx   = "EVX"   // Everex
	Fct   = "FCT"   // Factom                   https://coinmarketcap.com/currencies/factom/
	Flo   = "FLO"   // FlorinCoin               https://coinmarketcap.com/currencies/florincoin/
	Ftc   = "FTC"   // Feathercoin
	Fuel  = "FUEL"  // Etherparty
	Fun   = "FUN"   // FunFair                  https://coinmarketcap.com/currencies/funfair/
	Game  = "GAME"  // GameCredits
	Gbg   = "GBG"   // Golos Gold               https://coinmarketcap.com/currencies/golos-gold/
	Gld   = "GLD"   // GoldCoin
	Gno   = "GNO"   // Gnosis
	Gnt   = "GNT"   // Golem                    https://coinmarketcap.com/currencies/golem-network-tokens/
	Grs   = "GRS"   // Groestlcoin
	Gup   = "GUP"   // Matchpool                https://coinmarketcap.com/currencies/guppy/
	Hmq   = "HMQ"   // Humaniq                  https://coinmarketcap.com/currencies/humaniq/
	Hsr   = "HSR"   // Hshare
	Hyp   = "HYP"   // HyperStake
	Icn   = "ICN"   // Iconomi
	Infx  = "INFX"  // Influxcoin               https://coinmarketcap.com/currencies/influxcoin/
	Iop   = "IOP"   // Internet of People       https://coinmarketcap.com/currencies/internet-of-people/
	Iota  = "IOTA"  // Iota
	Ipbc  = "IPBC"
	Knc   = "KNC"   // Kyber Network
	Kore  = "KORE"  // Kore
	Lgd   = "LGD"   // Legends Room             https://coinmarketcap.com/currencies/legends-room/
	Lsk   = "LSK"   // Lisk
	Ltc   = "LTC"   // Litecoin
	Lun   = "LUN"   // Lunyr                    https://coinmarketcap.com/currencies/lunyr/
	Maid  = "MAID"  // MaidSafeCoin             https://coinmarketcap.com/currencies/maidsafecoin/
	Mana  = "MANA"  // Decentraland             https://coinmarketcap.com/currencies/decentraland/
	Mco   = "MCO"   // Monaco                   https://coinmarketcap.com/currencies/monaco/
	Meme  = "MEME"  // Memetic / PepeCoin       https://coinmarketcap.com/currencies/memetic/
	Mer   = "MER"   // Mercury                  https://coinmarketcap.com/currencies/mercury/
	Mln   = "MLN"   // Melon
	Mona  = "MONA"  // MonaCoin
	Mtl   = "MTL"   // Metal                    https://coinmarketcap.com/currencies/metal/
	Mue   = "MUE"   // MonetaryUnit             https://coinmarketcap.com/currencies/monetaryunit/
	Myst  = "MYST"  // Mysterium                https://coinmarketcap.com/currencies/mysterium/
	Nav   = "NAV"   // NAV Coin                 https://coinmarketcap.com/currencies/nav-coin/
	Neo   = "NEO"   // Neo
	Nlg   = "NLG"   // Gulden
	Nmc   = "NMC"   // Namecoin
	Nmr   = "NMR"   // Numeraire                https://coinmarketcap.com/currencies/numeraire/
	Nxt   = "NXT"   // Nxt
	Omg   = "OMG"   // OmiseGO
	Omni  = "OMNI"  // Omni                     https://coinmarketcap.com/currencies/omni/
	Part  = "PART"  // Particl                  https://coinmarketcap.com/currencies/particl/
	Pay   = "PAY"   // TenX                     https://coinmarketcap.com/currencies/tenx/
	Pivx  = "PIVX"  // PIVX                     https://coinmarketcap.com/currencies/pivx/
	Pnd   = "PND"   // Pandacoin
	Pot   = "POT"   // PotCoin
	Powr  = "POWR"  // Power Ledger             https://coinmarketcap.com/currencies/power-ledger/
	Ppc   = "PPC"   // Peercoin
	Ptc   = "PTC"   // Pesetacoin
	Ptoy  = "PTOY"  // Patientory               https://coinmarketcap.com/currencies/patientory/
	Qash  = "QASH"  // Qash                     https://coinmarketcap.com/currencies/qash/
	Qrk   = "QRK"   // Quark
	Qrl   = "QRL"   // Quantum Resistant Ledger https://coinmarketcap.com/currencies/quantum-resistant-ledger/
	Qtum  = "QTUM"  // Qtum                     https://coinmarketcap.com/currencies/qtum/
	Rby   = "RBY"   // Rubycoin
	Rcn   = "RCN"   // Ripio Credit Network     https://coinmarketcap.com/currencies/ripio-credit-network/
	Rdd   = "RDD"   // ReddCoin
	Rep   = "REP"   // Augur
	Rlc   = "RLC"   // iExec RLC                https://coinmarketcap.com/currencies/rlc/
	Salt  = "SALT"  // SALT                     https://coinmarketcap.com/currencies/salt/
	Sc    = "SC"    // Siacoin                  https://coinmarketcap.com/currencies/siacoin/
	Slr   = "SLR"   // SolarCoin
	Sls   = "SLS"   // SaluS                    https://coinmarketcap.com/currencies/salus/
	Snt   = "SNT"   // Status                   https://coinmarketcap.com/currencies/status/
	Srn   = "SRN"   // SIRIN LABS Token         https://coinmarketcap.com/currencies/sirin-labs-token/
	Start = "START" // Startcoin
	Storj = "STORJ" // Storj                    https://coinmarketcap.com/currencies/storj/
	Strat = "STRAT" // Stratis                  https://coinmarketcap.com/currencies/stratis/
	Thc   = "THC"   // HempCoin
	Tix   = "TIX"   // Blocktix                 https://coinmarketcap.com/currencies/blocktix/
	Trst  = "TRST"  // WeTrust                  https://coinmarketcap.com/currencies/trust/
	Trust = "TRUST" // TrustPlus
	Trx   = "TRX"   // TRON                     https://coinmarketcap.com/currencies/tron/
	Ubtc  = "UBTC"  // United Bitcoin
	Ukg   = "UKG"   // Unikoin Gold             https://coinmarketcap.com/currencies/unikoin-gold/
	Vib   = "VIB"   // Viberate                 https://coinmarketcap.com/currencies/viberate/
	Vrc   = "VRC"   // VeriCoin
	Vrm   = "VRM"   // VeriumReserve            https://coinmarketcap.com/currencies/veriumreserve/
	Vtc   = "VTC"   // Vertcoin
	Vtr   = "VTR"   // vTorrent                 https://coinmarketcap.com/currencies/vtorrent/
	Waves = "WAVES" // Waves
	Wings = "WINGS" // Wings                    https://coinmarketcap.com/currencies/wings/
	Xcn   = "XCN"   // Cryptonite
	Xdn   = "XDN"   // DigitalNote
	Xel   = "XEL"   // Elastic                  https://coinmarketcap.com/currencies/elastic/
	Xem   = "XEM"   // NEM
	Xlm   = "XLM"   // stellar, lumens
	Xmr   = "XMR"   // Monero
	Xmy   = "XMY"   // Myriad
	Xpm   = "XPM"   // Primecoin
	Xpy   = "XPY"   // PayCoin
	Xvg   = "XVG"   // Verge                    https://coinmarketcap.com/currencies/verge/
	Xwc   = "XWC"   // WhiteCoin
	Xzc   = "XZC"   // ZCoin
	Zcl   = "ZCL"   // ZClassic                 https://coinmarketcap.com/currencies/zclassic/
	Zec   = "ZEC"   // Zcash

	// shit
	Kfee = "KFEE" // Kraken fee
	Usdt = "USDT" // Tether
	Xrp  = "XRP"  // Ripple
)
