package symbols

const (
	// fiat
	Aud = "AUD"
	Cad = "CAD"
	Clp = "CLP"
	Cny = "CNY"
	Cop = "COP"
	Eur = "EUR"
	Gbp = "GBP"
	Hkd = "HKD"
	Idr = "IDR"
	Jpy = "JPY"
	Krw = "KRW"
	Myr = "MYR"
	Ngn = "NGN"
	Nzd = "NZD"
	Pen = "PEN"
	Php = "PHP"
	Pln = "PLN"
	Sgd = "SGD"
	Thb = "THB"
	Usd = "USD"
	Zar = "ZAR"

	// crypto
	Aur   = "AUR"   // Auroracoin
	Bch   = "BCH"   // Bcash
	Blk   = "BLK"   // BlackCoin
	Btc   = "BTC"   // Bitcoin
	Btg   = "BTG"   // Bgold
	Bts   = "BTS"   // BitShares
	Cloak = "CLOAK" // CloakCoin
	Cure  = "CURE"  // Curecoin
	Dash  = "DASH"  // Dash
	Doge  = "DOGE"  // Dogecoin
	Efl   = "EFL"   // e-Gulden
	Emc2  = "EMC2"  // Einsteinium
	Enrg  = "ENRG"  // Energycoin
	Eos   = "EOS"   // EOS
	Erc   = "ERC"   // EuropeCoin
	Etc   = "ETC"   // Ethereum Classic
	Eth   = "ETH"   // Ethereum
	Evx   = "EVX"   // Everex
	Ftc   = "FTC"   // Feathercoin
	Fuel  = "FUEL"  // Etherparty
	Game  = "GAME"  // GameCredits
	Gld   = "GLD"   // GoldCoin
	Gno   = "GNO"   // Gnosis
	Grs   = "GRS"   // Groestlcoin
	Hsr   = "HSR"   // Hshare
	Hyp   = "HYP"   // HyperStake
	Icn   = "ICN"   // Iconomi
	Iota  = "IOTA"  // Iota
	Knc   = "KNC"   // Kyber Network
	Kore  = "KORE"  // Kore
	Lsk   = "LSK"   // Lisk
	Ltc   = "LTC"   // Litecoin
	Mln   = "MLN"   // Melon
	Mona  = "MONA"  // MonaCoin
	Neo   = "NEO"   // Neo
	Nlg   = "NLG"   // Gulden
	Nmc   = "NMC"   // Namecoin
	Nxt   = "NXT"   // Nxt
	Omg   = "OMG"   // OmiseGO
	Pnd   = "PND"   // Pandacoin
	Pot   = "POT"   // PotCoin
	Ppc   = "PPC"   // Peercoin
	Ptc   = "PTC"   // Pesetacoin
	Qrk   = "QRK"   // Quark
	Rby   = "RBY"   // Rubycoin
	Rdd   = "RDD"   // ReddCoin
	Rep   = "REP"   // Augur
	Slr   = "SLR"   // SolarCoin
	Start = "START" // Startcoin
	Thc   = "THC"   // HempCoin
	Trust = "TRUST" // TrustPlus
	Ubtc  = "UBTC"  // United Bitcoin
	Vrc   = "VRC"   // VeriCoin
	Vtc   = "VTC"   // Vertcoin
	Waves = "WAVES" // Waves
	Xcn   = "XCN"   // Cryptonite
	Xdn   = "XDN"   // DigitalNote
	Xem   = "XEM"   // NEM
	Xlm   = "XLM"   // stellar, lumens
	Xmr   = "XMR"   // Monero
	Xmy   = "XMY"   // Myriad
	Xpm   = "XPM"   // Primecoin
	Xpy   = "XPY"   // PayCoin
	Xwc   = "XWC"   // WhiteCoin
	Xzc   = "XZC"   // ZCoin
	Zec   = "ZEC"   // Zcash

	// shit
	Usdt = "USDT" // Tether
	Xrp  = "XRP"  // Ripple
	Kfee = "KFEE" // Kraken fee
)
